# Retirement Planner

For this problem, you will be writing a "retirement savings" calculator. We will remove the effects of inflation by keeping everything in "today's dollars" and using a "rate of return" that is in terms of "more than inflation." 
 
## Setup 

Create a new file called "retirement.py".

Copy-paste the following scaffolding into the file:

```python
# calculate retirement savings
#  start_age is the age (in months) when we start the calculation
#  initial is the initially saved balance at the start
#  working is a three tuple (months, contribution, rate of return)
#  retired is a three tuple (months, contribution, rate of return)
def calculateRetirement(start_age, initial, working, retired):
    pass


def main():
    working = (489, 1000, 0.045 / 12)
    retired = (384, -4000, 0.01 / 12)
    calculateRetirement(327, 21345, working, retired)

if __name__ == "__main__":
    main()

```

## Write Your Calculator

We're going to model both savings (while working) and expenditure (while retired). It turns out that both of these require the same basic information, so we will use a tuple to represent that. 

This tuple has three fields:

1. an integer "months" for the number of months it is applicable to;
2. a floating point number "contribution" for how many dollars are
    contributed (or spent if negative) from the account per month;
3. a floating point number "rate_of_return" for the rate of returns
    (which we will assume to be "after inflation").

Then we will write the function:

```python
    calculateRetirement(start_age,  #in months
                        initial,    #initial savings in dollars
                        working,    #info about working
                        retired)    #info about being retired
```

This functions job is to print out the person's retirement account balance in each month of their life — presumably counting up as they are working and contributing, and counting down after they retire and begin to draw down their savings. For example, a block of the output for a person who worked till 68 then retired might look like:

```
[more output cut for space]

Age  67 month  7 you have $149,6040.99
Age  67 month  8 you have $150,2651.14
Age  67 month  9 you have $150,9286.09
Age  67 month 10 you have $151,5945.91
Age  67 month 11 you have $152,2630.71
Age  68 month  0 you have $152,9340.57
Age  68 month  1 you have $152,6615.02
Age  68 month  2 you have $152,3887.20
Age  68 month  3 you have $152,1157.11
Age  68 month  4 you have $151,8424.74
Age  68 month  5 you have $151,5690.09
Age  68 month  6 you have $151,2953.17
Age  68 month  7 you have $151,0213.96
Age  68 month  8 you have $150,7472.47

[more output cut for space]

```

Finally, the function should return the amount of money in the retirement fund when it finishes running.

Given that goal, the function really has to perform two tasks (which are similar---look for a chance to abstract something out into a function!).

### Job 1: Update Balance While Working

First, it should compute your retirement account balance each month while you are working. To do this, you need to calculate the account balance increase from returns (`balance * rate of return`), and add that to the current balance. You then need to add the monthly contribution to the balance.

For example, if you have \$1,000 in the account, earn a 0.5% rate of return per month, and contribute $100 per month, you would compute `1000 * 0.005 = $5` in interest earned. You would then add this plus the monthly contribution to the balance to end up with \$1105 in the account at the end of the month. 

At the start of each month (before the balance changes), you should print out the current balance with the following format helpers:

```python
f"Age {age_in_years:3d} month {age_in_months:2d} you have ${balance:,.2f}"
```

The first two format conversions are the savers age in years and months. The third format conversion is the account balance. This calculation goes on for the number of months specified in the "working" tuple. For a reminder on how f-strings work, [check here](../../notebooks/other/fstrings.ipynb).

### Job 2: Update Balance While Retired

Second, you should perform a very similar calculation for each month of retirement. The difference here is that you will use the information in the "retired" tuple instead of the information in the "working"
tuple. As with working, you should print out the same information as before.

**Hint:** since you are performing a very similar computation, think about how you can abstract that part out into a function, and reuse it, rather than rewriting it. 

Note that we have provided you with a main function that calls your function to do the following calculations:

```
Working:
--------
Months: 489
Per Month Savings: $1000
Rate of Return:  4.5% per year (0.045/12 per month) 
                [above inflation]
Retired:
--------
Months: 384
Per Month Spending: -4000
Rate of Return: 1% per year ( 0.01/12 per month) 
                [above inflation]
Starting conditions:
-------------------
Age: 327 months (27 years, 3 months)
Savings: $21,345
```

We call this `main` function under

```python
if __name__ == "__main__":
```

so that it only runs if this module is run as the main program, and not loaded as part of something else (e.g., if we load it into the grader to run other test cases!)

From now on, you should follow this practice.

## Check Your Work 

Run your code. The output you get should match the (very long) output pasted down below. See details on how to check it further down. 

## Submit Your Assignment 

Note that we will test your code with a variety of other retirement scenarios (months, initial values,
rates of return, etc).  If your code matches the local test cases but does not pass the grader, please check if you hard coded any values in your `calculateRetirement` function where you should have used the values in the parameters.

**MAKE SURE YOUR `calculateRetirement` FUNCTION RETURNS THE FINAL BALANCE AFTER ALL MONTHS OF RETIREMENT HAVE PASSED**

This returned balance should be the balance AFTER the last month, which means it will be slightly different from the last value printed.


## Expected Output

Your function should generate the following output. 

If this feels like too much output to check yourself, you can use the `diff` function in VS Code to compare your output to this. `diff` is an incredibly useful utility that compares two text files and only shows you the places they are different. In this case, it will show you where your results differ from the expected outputs, but the tool also becomes very useful when collaborating on code with other people — when a colleague makes a change to a big file, `diff` makes it easy to see *just* what they've changed.

Here's a GIF showing how you can use `diff` yourself. In it, I create a text file, copy-paste the expected output into that file, open and run my python file, copy-paste the output into a second file, then as VS Code to compare the two files. 

As you can see, only the first line is colored because in the reference text `world` is capitalized and in my Python output it is not. All identical lines are in grey.

![diffing two files](./images/diff_in_vscode.gif)


### Output

```
Age  27 month  3 you have $21,345.00
Age  27 month  4 you have $22,425.04
Age  27 month  5 you have $23,509.14
Age  27 month  6 you have $24,597.30
Age  27 month  7 you have $25,689.54
Age  27 month  8 you have $26,785.87
Age  27 month  9 you have $27,886.32
Age  27 month 10 you have $28,990.89
Age  27 month 11 you have $30,099.61
Age  28 month  0 you have $31,212.48
Age  28 month  1 you have $32,329.53
Age  28 month  2 you have $33,450.77
Age  28 month  3 you have $34,576.21
Age  28 month  4 you have $35,705.87
Age  28 month  5 you have $36,839.76
Age  28 month  6 you have $37,977.91
Age  28 month  7 you have $39,120.33
Age  28 month  8 you have $40,267.03
Age  28 month  9 you have $41,418.03
Age  28 month 10 you have $42,573.35
Age  28 month 11 you have $43,733.00
Age  29 month  0 you have $44,897.00
Age  29 month  1 you have $46,065.36
Age  29 month  2 you have $47,238.11
Age  29 month  3 you have $48,415.25
Age  29 month  4 you have $49,596.81
Age  29 month  5 you have $50,782.80
Age  29 month  6 you have $51,973.23
Age  29 month  7 you have $53,168.13
Age  29 month  8 you have $54,367.51
Age  29 month  9 you have $55,571.39
Age  29 month 10 you have $56,779.78
Age  29 month 11 you have $57,992.71
Age  30 month  0 you have $59,210.18
Age  30 month  1 you have $60,432.22
Age  30 month  2 you have $61,658.84
Age  30 month  3 you have $62,890.06
Age  30 month  4 you have $64,125.90
Age  30 month  5 you have $65,366.37
Age  30 month  6 you have $66,611.49
Age  30 month  7 you have $67,861.29
Age  30 month  8 you have $69,115.77
Age  30 month  9 you have $70,374.95
Age  30 month 10 you have $71,638.86
Age  30 month 11 you have $72,907.50
Age  31 month  0 you have $74,180.90
Age  31 month  1 you have $75,459.08
Age  31 month  2 you have $76,742.05
Age  31 month  3 you have $78,029.84
Age  31 month  4 you have $79,322.45
Age  31 month  5 you have $80,619.91
Age  31 month  6 you have $81,922.23
Age  31 month  7 you have $83,229.44
Age  31 month  8 you have $84,541.55
Age  31 month  9 you have $85,858.58
Age  31 month 10 you have $87,180.55
Age  31 month 11 you have $88,507.48
Age  32 month  0 you have $89,839.38
Age  32 month  1 you have $91,176.28
Age  32 month  2 you have $92,518.19
Age  32 month  3 you have $93,865.13
Age  32 month  4 you have $95,217.13
Age  32 month  5 you have $96,574.19
Age  32 month  6 you have $97,936.35
Age  32 month  7 you have $99,303.61
Age  32 month  8 you have $100,676.00
Age  32 month  9 you have $102,053.53
Age  32 month 10 you have $103,436.23
Age  32 month 11 you have $104,824.12
Age  33 month  0 you have $106,217.21
Age  33 month  1 you have $107,615.52
Age  33 month  2 you have $109,019.08
Age  33 month  3 you have $110,427.90
Age  33 month  4 you have $111,842.01
Age  33 month  5 you have $113,261.41
Age  33 month  6 you have $114,686.14
Age  33 month  7 you have $116,116.22
Age  33 month  8 you have $117,551.65
Age  33 month  9 you have $118,992.47
Age  33 month 10 you have $120,438.69
Age  33 month 11 you have $121,890.34
Age  34 month  0 you have $123,347.43
Age  34 month  1 you have $124,809.98
Age  34 month  2 you have $126,278.02
Age  34 month  3 you have $127,751.56
Age  34 month  4 you have $129,230.63
Age  34 month  5 you have $130,715.24
Age  34 month  6 you have $132,205.43
Age  34 month  7 you have $133,701.20
Age  34 month  8 you have $135,202.58
Age  34 month  9 you have $136,709.59
Age  34 month 10 you have $138,222.25
Age  34 month 11 you have $139,740.58
Age  35 month  0 you have $141,264.61
Age  35 month  1 you have $142,794.35
Age  35 month  2 you have $144,329.83
Age  35 month  3 you have $145,871.06
Age  35 month  4 you have $147,418.08
Age  35 month  5 you have $148,970.90
Age  35 month  6 you have $150,529.54
Age  35 month  7 you have $152,094.03
Age  35 month  8 you have $153,664.38
Age  35 month  9 you have $155,240.62
Age  35 month 10 you have $156,822.77
Age  35 month 11 you have $158,410.86
Age  36 month  0 you have $160,004.90
Age  36 month  1 you have $161,604.92
Age  36 month  2 you have $163,210.93
Age  36 month  3 you have $164,822.98
Age  36 month  4 you have $166,441.06
Age  36 month  5 you have $168,065.22
Age  36 month  6 you have $169,695.46
Age  36 month  7 you have $171,331.82
Age  36 month  8 you have $172,974.31
Age  36 month  9 you have $174,622.97
Age  36 month 10 you have $176,277.80
Age  36 month 11 you have $177,938.84
Age  37 month  0 you have $179,606.12
Age  37 month  1 you have $181,279.64
Age  37 month  2 you have $182,959.44
Age  37 month  3 you have $184,645.53
Age  37 month  4 you have $186,337.96
Age  37 month  5 you have $188,036.72
Age  37 month  6 you have $189,741.86
Age  37 month  7 you have $191,453.39
Age  37 month  8 you have $193,171.34
Age  37 month  9 you have $194,895.74
Age  37 month 10 you have $196,626.59
Age  37 month 11 you have $198,363.94
Age  38 month  0 you have $200,107.81
Age  38 month  1 you have $201,858.21
Age  38 month  2 you have $203,615.18
Age  38 month  3 you have $205,378.74
Age  38 month  4 you have $207,148.91
Age  38 month  5 you have $208,925.72
Age  38 month  6 you have $210,709.19
Age  38 month  7 you have $212,499.35
Age  38 month  8 you have $214,296.22
Age  38 month  9 you have $216,099.83
Age  38 month 10 you have $217,910.21
Age  38 month 11 you have $219,727.37
Age  39 month  0 you have $221,551.35
Age  39 month  1 you have $223,382.16
Age  39 month  2 you have $225,219.85
Age  39 month  3 you have $227,064.42
Age  39 month  4 you have $228,915.91
Age  39 month  5 you have $230,774.35
Age  39 month  6 you have $232,639.75
Age  39 month  7 you have $234,512.15
Age  39 month  8 you have $236,391.57
Age  39 month  9 you have $238,278.04
Age  39 month 10 you have $240,171.58
Age  39 month 11 you have $242,072.23
Age  40 month  0 you have $243,980.00
Age  40 month  1 you have $245,894.92
Age  40 month  2 you have $247,817.03
Age  40 month  3 you have $249,746.34
Age  40 month  4 you have $251,682.89
Age  40 month  5 you have $253,626.70
Age  40 month  6 you have $255,577.80
Age  40 month  7 you have $257,536.22
Age  40 month  8 you have $259,501.98
Age  40 month  9 you have $261,475.11
Age  40 month 10 you have $263,455.64
Age  40 month 11 you have $265,443.60
Age  41 month  0 you have $267,439.01
Age  41 month  1 you have $269,441.91
Age  41 month  2 you have $271,452.32
Age  41 month  3 you have $273,470.26
Age  41 month  4 you have $275,495.78
Age  41 month  5 you have $277,528.89
Age  41 month  6 you have $279,569.62
Age  41 month  7 you have $281,618.01
Age  41 month  8 you have $283,674.07
Age  41 month  9 you have $285,737.85
Age  41 month 10 you have $287,809.37
Age  41 month 11 you have $289,888.65
Age  42 month  0 you have $291,975.74
Age  42 month  1 you have $294,070.65
Age  42 month  2 you have $296,173.41
Age  42 month  3 you have $298,284.06
Age  42 month  4 you have $300,402.63
Age  42 month  5 you have $302,529.14
Age  42 month  6 you have $304,663.62
Age  42 month  7 you have $306,806.11
Age  42 month  8 you have $308,956.63
Age  42 month  9 you have $311,115.22
Age  42 month 10 you have $313,281.90
Age  42 month 11 you have $315,456.71
Age  43 month  0 you have $317,639.67
Age  43 month  1 you have $319,830.82
Age  43 month  2 you have $322,030.18
Age  43 month  3 you have $324,237.80
Age  43 month  4 you have $326,453.69
Age  43 month  5 you have $328,677.89
Age  43 month  6 you have $330,910.43
Age  43 month  7 you have $333,151.35
Age  43 month  8 you have $335,400.66
Age  43 month  9 you have $337,658.42
Age  43 month 10 you have $339,924.64
Age  43 month 11 you have $342,199.35
Age  44 month  0 you have $344,482.60
Age  44 month  1 you have $346,774.41
Age  44 month  2 you have $349,074.82
Age  44 month  3 you have $351,383.85
Age  44 month  4 you have $353,701.54
Age  44 month  5 you have $356,027.92
Age  44 month  6 you have $358,363.02
Age  44 month  7 you have $360,706.88
Age  44 month  8 you have $363,059.53
Age  44 month  9 you have $365,421.01
Age  44 month 10 you have $367,791.33
Age  44 month 11 you have $370,170.55
Age  45 month  0 you have $372,558.69
Age  45 month  1 you have $374,955.79
Age  45 month  2 you have $377,361.87
Age  45 month  3 you have $379,776.98
Age  45 month  4 you have $382,201.14
Age  45 month  5 you have $384,634.40
Age  45 month  6 you have $387,076.78
Age  45 month  7 you have $389,528.31
Age  45 month  8 you have $391,989.04
Age  45 month  9 you have $394,459.00
Age  45 month 10 you have $396,938.22
Age  45 month 11 you have $399,426.74
Age  46 month  0 you have $401,924.59
Age  46 month  1 you have $404,431.81
Age  46 month  2 you have $406,948.43
Age  46 month  3 you have $409,474.49
Age  46 month  4 you have $412,010.02
Age  46 month  5 you have $414,555.05
Age  46 month  6 you have $417,109.63
Age  46 month  7 you have $419,673.80
Age  46 month  8 you have $422,247.57
Age  46 month  9 you have $424,831.00
Age  46 month 10 you have $427,424.12
Age  46 month 11 you have $430,026.96
Age  47 month  0 you have $432,639.56
Age  47 month  1 you have $435,261.96
Age  47 month  2 you have $437,894.19
Age  47 month  3 you have $440,536.29
Age  47 month  4 you have $443,188.30
Age  47 month  5 you have $445,850.26
Age  47 month  6 you have $448,522.20
Age  47 month  7 you have $451,204.16
Age  47 month  8 you have $453,896.17
Age  47 month  9 you have $456,598.28
Age  47 month 10 you have $459,310.53
Age  47 month 11 you have $462,032.94
Age  48 month  0 you have $464,765.56
Age  48 month  1 you have $467,508.43
Age  48 month  2 you have $470,261.59
Age  48 month  3 you have $473,025.07
Age  48 month  4 you have $475,798.92
Age  48 month  5 you have $478,583.16
Age  48 month  6 you have $481,377.85
Age  48 month  7 you have $484,183.02
Age  48 month  8 you have $486,998.70
Age  48 month  9 you have $489,824.95
Age  48 month 10 you have $492,661.79
Age  48 month 11 you have $495,509.27
Age  49 month  0 you have $498,367.43
Age  49 month  1 you have $501,236.31
Age  49 month  2 you have $504,115.95
Age  49 month  3 you have $507,006.38
Age  49 month  4 you have $509,907.66
Age  49 month  5 you have $512,819.81
Age  49 month  6 you have $515,742.88
Age  49 month  7 you have $518,676.92
Age  49 month  8 you have $521,621.96
Age  49 month  9 you have $524,578.04
Age  49 month 10 you have $527,545.21
Age  49 month 11 you have $530,523.50
Age  50 month  0 you have $533,512.97
Age  50 month  1 you have $536,513.64
Age  50 month  2 you have $539,525.57
Age  50 month  3 you have $542,548.79
Age  50 month  4 you have $545,583.34
Age  50 month  5 you have $548,629.28
Age  50 month  6 you have $551,686.64
Age  50 month  7 you have $554,755.47
Age  50 month  8 you have $557,835.80
Age  50 month  9 you have $560,927.68
Age  50 month 10 you have $564,031.16
Age  50 month 11 you have $567,146.28
Age  51 month  0 you have $570,273.08
Age  51 month  1 you have $573,411.60
Age  51 month  2 you have $576,561.90
Age  51 month  3 you have $579,724.00
Age  51 month  4 you have $582,897.97
Age  51 month  5 you have $586,083.83
Age  51 month  6 you have $589,281.65
Age  51 month  7 you have $592,491.46
Age  51 month  8 you have $595,713.30
Age  51 month  9 you have $598,947.22
Age  51 month 10 you have $602,193.28
Age  51 month 11 you have $605,451.50
Age  52 month  0 you have $608,721.94
Age  52 month  1 you have $612,004.65
Age  52 month  2 you have $615,299.67
Age  52 month  3 you have $618,607.04
Age  52 month  4 you have $621,926.82
Age  52 month  5 you have $625,259.04
Age  52 month  6 you have $628,603.77
Age  52 month  7 you have $631,961.03
Age  52 month  8 you have $635,330.88
Age  52 month  9 you have $638,713.37
Age  52 month 10 you have $642,108.55
Age  52 month 11 you have $645,516.46
Age  53 month  0 you have $648,937.14
Age  53 month  1 you have $652,370.66
Age  53 month  2 you have $655,817.05
Age  53 month  3 you have $659,276.36
Age  53 month  4 you have $662,748.65
Age  53 month  5 you have $666,233.95
Age  53 month  6 you have $669,732.33
Age  53 month  7 you have $673,243.83
Age  53 month  8 you have $676,768.49
Age  53 month  9 you have $680,306.37
Age  53 month 10 you have $683,857.52
Age  53 month 11 you have $687,421.99
Age  54 month  0 you have $690,999.82
Age  54 month  1 you have $694,591.07
Age  54 month  2 you have $698,195.79
Age  54 month  3 you have $701,814.02
Age  54 month  4 you have $705,445.82
Age  54 month  5 you have $709,091.25
Age  54 month  6 you have $712,750.34
Age  54 month  7 you have $716,423.15
Age  54 month  8 you have $720,109.74
Age  54 month  9 you have $723,810.15
Age  54 month 10 you have $727,524.44
Age  54 month 11 you have $731,252.66
Age  55 month  0 you have $734,994.85
Age  55 month  1 you have $738,751.08
Age  55 month  2 you have $742,521.40
Age  55 month  3 you have $746,305.86
Age  55 month  4 you have $750,104.50
Age  55 month  5 you have $753,917.39
Age  55 month  6 you have $757,744.58
Age  55 month  7 you have $761,586.13
Age  55 month  8 you have $765,442.07
Age  55 month  9 you have $769,312.48
Age  55 month 10 you have $773,197.40
Age  55 month 11 you have $777,096.89
Age  56 month  0 you have $781,011.01
Age  56 month  1 you have $784,939.80
Age  56 month  2 you have $788,883.32
Age  56 month  3 you have $792,841.64
Age  56 month  4 you have $796,814.79
Age  56 month  5 you have $800,802.85
Age  56 month  6 you have $804,805.86
Age  56 month  7 you have $808,823.88
Age  56 month  8 you have $812,856.97
Age  56 month  9 you have $816,905.18
Age  56 month 10 you have $820,968.58
Age  56 month 11 you have $825,047.21
Age  57 month  0 you have $829,141.14
Age  57 month  1 you have $833,250.42
Age  57 month  2 you have $837,375.10
Age  57 month  3 you have $841,515.26
Age  57 month  4 you have $845,670.94
Age  57 month  5 you have $849,842.21
Age  57 month  6 you have $854,029.12
Age  57 month  7 you have $858,231.73
Age  57 month  8 you have $862,450.10
Age  57 month  9 you have $866,684.28
Age  57 month 10 you have $870,934.35
Age  57 month 11 you have $875,200.35
Age  58 month  0 you have $879,482.36
Age  58 month  1 you have $883,780.41
Age  58 month  2 you have $888,094.59
Age  58 month  3 you have $892,424.95
Age  58 month  4 you have $896,771.54
Age  58 month  5 you have $901,134.43
Age  58 month  6 you have $905,513.69
Age  58 month  7 you have $909,909.36
Age  58 month  8 you have $914,321.52
Age  58 month  9 you have $918,750.23
Age  58 month 10 you have $923,195.54
Age  58 month 11 you have $927,657.53
Age  59 month  0 you have $932,136.24
Age  59 month  1 you have $936,631.75
Age  59 month  2 you have $941,144.12
Age  59 month  3 you have $945,673.41
Age  59 month  4 you have $950,219.69
Age  59 month  5 you have $954,783.01
Age  59 month  6 you have $959,363.45
Age  59 month  7 you have $963,961.06
Age  59 month  8 you have $968,575.91
Age  59 month  9 you have $973,208.07
Age  59 month 10 you have $977,857.60
Age  59 month 11 you have $982,524.57
Age  60 month  0 you have $987,209.04
Age  60 month  1 you have $991,911.07
Age  60 month  2 you have $996,630.74
Age  60 month  3 you have $100,1368.10
Age  60 month  4 you have $100,6123.23
Age  60 month  5 you have $101,0896.19
Age  60 month  6 you have $101,5687.06
Age  60 month  7 you have $102,0495.88
Age  60 month  8 you have $102,5322.74
Age  60 month  9 you have $103,0167.70
Age  60 month 10 you have $103,5030.83
Age  60 month 11 you have $103,9912.20
Age  61 month  0 you have $104,4811.87
Age  61 month  1 you have $104,9729.91
Age  61 month  2 you have $105,4666.40
Age  61 month  3 you have $105,9621.40
Age  61 month  4 you have $106,4594.98
Age  61 month  5 you have $106,9587.21
Age  61 month  6 you have $107,4598.16
Age  61 month  7 you have $107,9627.90
Age  61 month  8 you have $108,4676.51
Age  61 month  9 you have $108,9744.05
Age  61 month 10 you have $109,4830.59
Age  61 month 11 you have $109,9936.20
Age  62 month  0 you have $110,5060.96
Age  62 month  1 you have $111,0204.94
Age  62 month  2 you have $111,5368.21
Age  62 month  3 you have $112,0550.84
Age  62 month  4 you have $112,5752.91
Age  62 month  5 you have $113,0974.48
Age  62 month  6 you have $113,6215.63
Age  62 month  7 you have $114,1476.44
Age  62 month  8 you have $114,6756.98
Age  62 month  9 you have $115,2057.32
Age  62 month 10 you have $115,7377.53
Age  62 month 11 you have $116,2717.70
Age  63 month  0 you have $116,8077.89
Age  63 month  1 you have $117,3458.18
Age  63 month  2 you have $117,8858.65
Age  63 month  3 you have $118,4279.37
Age  63 month  4 you have $118,9720.42
Age  63 month  5 you have $119,5181.87
Age  63 month  6 you have $120,0663.80
Age  63 month  7 you have $120,6166.29
Age  63 month  8 you have $121,1689.41
Age  63 month  9 you have $121,7233.25
Age  63 month 10 you have $122,2797.87
Age  63 month 11 you have $122,8383.36
Age  64 month  0 you have $123,3989.80
Age  64 month  1 you have $123,9617.26
Age  64 month  2 you have $124,5265.83
Age  64 month  3 you have $125,0935.58
Age  64 month  4 you have $125,6626.58
Age  64 month  5 you have $126,2338.93
Age  64 month  6 you have $126,8072.71
Age  64 month  7 you have $127,3827.98
Age  64 month  8 you have $127,9604.83
Age  64 month  9 you have $128,5403.35
Age  64 month 10 you have $129,1223.61
Age  64 month 11 you have $129,7065.70
Age  65 month  0 you have $130,2929.70
Age  65 month  1 you have $130,8815.68
Age  65 month  2 you have $131,4723.74
Age  65 month  3 you have $132,0653.96
Age  65 month  4 you have $132,6606.41
Age  65 month  5 you have $133,2581.18
Age  65 month  6 you have $133,8578.36
Age  65 month  7 you have $134,4598.03
Age  65 month  8 you have $135,0640.27
Age  65 month  9 you have $135,6705.18
Age  65 month 10 you have $136,2792.82
Age  65 month 11 you have $136,8903.29
Age  66 month  0 you have $137,5036.68
Age  66 month  1 you have $138,1193.07
Age  66 month  2 you have $138,7372.54
Age  66 month  3 you have $139,3575.19
Age  66 month  4 you have $139,9801.10
Age  66 month  5 you have $140,6050.35
Age  66 month  6 you have $141,2323.04
Age  66 month  7 you have $141,8619.25
Age  66 month  8 you have $142,4939.07
Age  66 month  9 you have $143,1282.59
Age  66 month 10 you have $143,7649.90
Age  66 month 11 you have $144,4041.09
Age  67 month  0 you have $145,0456.25
Age  67 month  1 you have $145,6895.46
Age  67 month  2 you have $146,3358.81
Age  67 month  3 you have $146,9846.41
Age  67 month  4 you have $147,6358.33
Age  67 month  5 you have $148,2894.68
Age  67 month  6 you have $148,9455.53
Age  67 month  7 you have $149,6040.99
Age  67 month  8 you have $150,2651.14
Age  67 month  9 you have $150,9286.09
Age  67 month 10 you have $151,5945.91
Age  67 month 11 you have $152,2630.71
Age  68 month  0 you have $152,9340.57
Age  68 month  1 you have $152,6615.02
Age  68 month  2 you have $152,3887.20
Age  68 month  3 you have $152,1157.11
Age  68 month  4 you have $151,8424.74
Age  68 month  5 you have $151,5690.09
Age  68 month  6 you have $151,2953.17
Age  68 month  7 you have $151,0213.96
Age  68 month  8 you have $150,7472.47
Age  68 month  9 you have $150,4728.70
Age  68 month 10 you have $150,1982.64
Age  68 month 11 you have $149,9234.29
Age  69 month  0 you have $149,6483.65
Age  69 month  1 you have $149,3730.72
Age  69 month  2 you have $149,0975.50
Age  69 month  3 you have $148,8217.98
Age  69 month  4 you have $148,5458.16
Age  69 month  5 you have $148,2696.04
Age  69 month  6 you have $147,9931.62
Age  69 month  7 you have $147,7164.90
Age  69 month  8 you have $147,4395.87
Age  69 month  9 you have $147,1624.53
Age  69 month 10 you have $146,8850.89
Age  69 month 11 you have $146,6074.93
Age  70 month  0 you have $146,3296.66
Age  70 month  1 you have $146,0516.07
Age  70 month  2 you have $145,7733.17
Age  70 month  3 you have $145,4947.95
Age  70 month  4 you have $145,2160.40
Age  70 month  5 you have $144,9370.54
Age  70 month  6 you have $144,6578.35
Age  70 month  7 you have $144,3783.83
Age  70 month  8 you have $144,0986.98
Age  70 month  9 you have $143,8187.80
Age  70 month 10 you have $143,5386.29
Age  70 month 11 you have $143,2582.45
Age  71 month  0 you have $142,9776.27
Age  71 month  1 you have $142,6967.75
Age  71 month  2 you have $142,4156.89
Age  71 month  3 you have $142,1343.68
Age  71 month  4 you have $141,8528.14
Age  71 month  5 you have $141,5710.24
Age  71 month  6 you have $141,2890.00
Age  71 month  7 you have $141,0067.41
Age  71 month  8 you have $140,7242.47
Age  71 month  9 you have $140,4415.17
Age  71 month 10 you have $140,1585.52
Age  71 month 11 you have $139,8753.50
Age  72 month  0 you have $139,5919.13
Age  72 month  1 you have $139,3082.40
Age  72 month  2 you have $139,0243.30
Age  72 month  3 you have $138,7401.84
Age  72 month  4 you have $138,4558.00
Age  72 month  5 you have $138,1711.80
Age  72 month  6 you have $137,8863.23
Age  72 month  7 you have $137,6012.28
Age  72 month  8 you have $137,3158.96
Age  72 month  9 you have $137,0303.26
Age  72 month 10 you have $136,7445.18
Age  72 month 11 you have $136,4584.71
Age  73 month  0 you have $136,1721.87
Age  73 month  1 you have $135,8856.64
Age  73 month  2 you have $135,5989.02
Age  73 month  3 you have $135,3119.01
Age  73 month  4 you have $135,0246.61
Age  73 month  5 you have $134,7371.81
Age  73 month  6 you have $134,4494.62
Age  73 month  7 you have $134,1615.03
Age  73 month  8 you have $133,8733.05
Age  73 month  9 you have $133,5848.66
Age  73 month 10 you have $133,2961.87
Age  73 month 11 you have $133,0072.67
Age  74 month  0 you have $132,7181.06
Age  74 month  1 you have $132,4287.04
Age  74 month  2 you have $132,1390.62
Age  74 month  3 you have $131,8491.78
Age  74 month  4 you have $131,5590.52
Age  74 month  5 you have $131,2686.84
Age  74 month  6 you have $130,9780.75
Age  74 month  7 you have $130,6872.23
Age  74 month  8 you have $130,3961.29
Age  74 month  9 you have $130,1047.93
Age  74 month 10 you have $129,8132.14
Age  74 month 11 you have $129,5213.91
Age  75 month  0 you have $129,2293.26
Age  75 month  1 you have $128,9370.17
Age  75 month  2 you have $128,6444.64
Age  75 month  3 you have $128,3516.68
Age  75 month  4 you have $128,0586.28
Age  75 month  5 you have $127,7653.43
Age  75 month  6 you have $127,4718.14
Age  75 month  7 you have $127,1780.41
Age  75 month  8 you have $126,8840.23
Age  75 month  9 you have $126,5897.59
Age  75 month 10 you have $126,2952.51
Age  75 month 11 you have $126,0004.97
Age  76 month  0 you have $125,7054.97
Age  76 month  1 you have $125,4102.52
Age  76 month  2 you have $125,1147.60
Age  76 month  3 you have $124,8190.23
Age  76 month  4 you have $124,5230.39
Age  76 month  5 you have $124,2268.08
Age  76 month  6 you have $123,9303.30
Age  76 month  7 you have $123,6336.05
Age  76 month  8 you have $123,3366.33
Age  76 month  9 you have $123,0394.14
Age  76 month 10 you have $122,7419.47
Age  76 month 11 you have $122,4442.32
Age  77 month  0 you have $122,1462.69
Age  77 month  1 you have $121,8480.57
Age  77 month  2 you have $121,5495.97
Age  77 month  3 you have $121,2508.88
Age  77 month  4 you have $120,9519.31
Age  77 month  5 you have $120,6527.24
Age  77 month  6 you have $120,3532.68
Age  77 month  7 you have $120,0535.63
Age  77 month  8 you have $119,7536.07
Age  77 month  9 you have $119,4534.02
Age  77 month 10 you have $119,1529.46
Age  77 month 11 you have $118,8522.40
Age  78 month  0 you have $118,5512.84
Age  78 month  1 you have $118,2500.77
Age  78 month  2 you have $117,9486.18
Age  78 month  3 you have $117,6469.09
Age  78 month  4 you have $117,3449.48
Age  78 month  5 you have $117,0427.35
Age  78 month  6 you have $116,7402.71
Age  78 month  7 you have $116,4375.55
Age  78 month  8 you have $116,1345.86
Age  78 month  9 you have $115,8313.65
Age  78 month 10 you have $115,5278.91
Age  78 month 11 you have $115,2241.64
Age  79 month  0 you have $114,9201.84
Age  79 month  1 you have $114,6159.51
Age  79 month  2 you have $114,3114.64
Age  79 month  3 you have $114,0067.24
Age  79 month  4 you have $113,7017.30
Age  79 month  5 you have $113,3964.81
Age  79 month  6 you have $113,0909.78
Age  79 month  7 you have $112,7852.21
Age  79 month  8 you have $112,4792.08
Age  79 month  9 you have $112,1729.41
Age  79 month 10 you have $111,8664.18
Age  79 month 11 you have $111,5596.40
Age  80 month  0 you have $111,2526.07
Age  80 month  1 you have $110,9453.17
Age  80 month  2 you have $110,6377.72
Age  80 month  3 you have $110,3299.70
Age  80 month  4 you have $110,0219.11
Age  80 month  5 you have $109,7135.96
Age  80 month  6 you have $109,4050.24
Age  80 month  7 you have $109,0961.95
Age  80 month  8 you have $108,7871.09
Age  80 month  9 you have $108,4777.65
Age  80 month 10 you have $108,1681.63
Age  80 month 11 you have $107,8583.03
Age  81 month  0 you have $107,5481.85
Age  81 month  1 you have $107,2378.08
Age  81 month  2 you have $106,9271.73
Age  81 month  3 you have $106,6162.79
Age  81 month  4 you have $106,3051.26
Age  81 month  5 you have $105,9937.14
Age  81 month  6 you have $105,6820.42
Age  81 month  7 you have $105,3701.10
Age  81 month  8 you have $105,0579.19
Age  81 month  9 you have $104,7454.67
Age  81 month 10 you have $104,4327.55
Age  81 month 11 you have $104,1197.82
Age  82 month  0 you have $103,8065.48
Age  82 month  1 you have $103,4930.54
Age  82 month  2 you have $103,1792.98
Age  82 month  3 you have $102,8652.81
Age  82 month  4 you have $102,5510.02
Age  82 month  5 you have $102,2364.61
Age  82 month  6 you have $101,9216.58
Age  82 month  7 you have $101,6065.93
Age  82 month  8 you have $101,2912.65
Age  82 month  9 you have $100,9756.74
Age  82 month 10 you have $100,6598.21
Age  82 month 11 you have $100,3437.04
Age  83 month  0 you have $100,0273.24
Age  83 month  1 you have $997,106.80
Age  83 month  2 you have $993,937.72
Age  83 month  3 you have $990,766.00
Age  83 month  4 you have $987,591.64
Age  83 month  5 you have $984,414.63
Age  83 month  6 you have $981,234.98
Age  83 month  7 you have $978,052.68
Age  83 month  8 you have $974,867.72
Age  83 month  9 you have $971,680.11
Age  83 month 10 you have $968,489.84
Age  83 month 11 you have $965,296.92
Age  84 month  0 you have $962,101.33
Age  84 month  1 you have $958,903.08
Age  84 month  2 you have $955,702.17
Age  84 month  3 you have $952,498.59
Age  84 month  4 you have $949,292.34
Age  84 month  5 you have $946,083.41
Age  84 month  6 you have $942,871.82
Age  84 month  7 you have $939,657.54
Age  84 month  8 you have $936,440.59
Age  84 month  9 you have $933,220.96
Age  84 month 10 you have $929,998.64
Age  84 month 11 you have $926,773.64
Age  85 month  0 you have $923,545.95
Age  85 month  1 you have $920,315.57
Age  85 month  2 you have $917,082.50
Age  85 month  3 you have $913,846.74
Age  85 month  4 you have $910,608.28
Age  85 month  5 you have $907,367.12
Age  85 month  6 you have $904,123.26
Age  85 month  7 you have $900,876.69
Age  85 month  8 you have $897,627.42
Age  85 month  9 you have $894,375.45
Age  85 month 10 you have $891,120.76
Age  85 month 11 you have $887,863.36
Age  86 month  0 you have $884,603.25
Age  86 month  1 you have $881,340.42
Age  86 month  2 you have $878,074.87
Age  86 month  3 you have $874,806.59
Age  86 month  4 you have $871,535.60
Age  86 month  5 you have $868,261.88
Age  86 month  6 you have $864,985.43
Age  86 month  7 you have $861,706.25
Age  86 month  8 you have $858,424.34
Age  86 month  9 you have $855,139.69
Age  86 month 10 you have $851,852.31
Age  86 month 11 you have $848,562.19
Age  87 month  0 you have $845,269.32
Age  87 month  1 you have $841,973.71
Age  87 month  2 you have $838,675.36
Age  87 month  3 you have $835,374.26
Age  87 month  4 you have $832,070.40
Age  87 month  5 you have $828,763.79
Age  87 month  6 you have $825,454.43
Age  87 month  7 you have $822,142.31
Age  87 month  8 you have $818,827.43
Age  87 month  9 you have $815,509.78
Age  87 month 10 you have $812,189.37
Age  87 month 11 you have $808,866.20
Age  88 month  0 you have $805,540.25
Age  88 month  1 you have $802,211.54
Age  88 month  2 you have $798,880.05
Age  88 month  3 you have $795,545.78
Age  88 month  4 you have $792,208.73
Age  88 month  5 you have $788,868.91
Age  88 month  6 you have $785,526.30
Age  88 month  7 you have $782,180.90
Age  88 month  8 you have $778,832.72
Age  88 month  9 you have $775,481.75
Age  88 month 10 you have $772,127.98
Age  88 month 11 you have $768,771.42
Age  89 month  0 you have $765,412.07
Age  89 month  1 you have $762,049.91
Age  89 month  2 you have $758,684.95
Age  89 month  3 you have $755,317.19
Age  89 month  4 you have $751,946.62
Age  89 month  5 you have $748,573.24
Age  89 month  6 you have $745,197.05
Age  89 month  7 you have $741,818.05
Age  89 month  8 you have $738,436.23
Age  89 month  9 you have $735,051.60
Age  89 month 10 you have $731,664.14
Age  89 month 11 you have $728,273.86
Age  90 month  0 you have $724,880.75
Age  90 month  1 you have $721,484.82
Age  90 month  2 you have $718,086.06
Age  90 month  3 you have $714,684.46
Age  90 month  4 you have $711,280.03
Age  90 month  5 you have $707,872.77
Age  90 month  6 you have $704,462.66
Age  90 month  7 you have $701,049.71
Age  90 month  8 you have $697,633.92
Age  90 month  9 you have $694,215.28
Age  90 month 10 you have $690,793.80
Age  90 month 11 you have $687,369.46
Age  91 month  0 you have $683,942.27
Age  91 month  1 you have $680,512.22
Age  91 month  2 you have $677,079.31
Age  91 month  3 you have $673,643.54
Age  91 month  4 you have $670,204.91
Age  91 month  5 you have $666,763.42
Age  91 month  6 you have $663,319.05
Age  91 month  7 you have $659,871.82
Age  91 month  8 you have $656,421.71
Age  91 month  9 you have $652,968.73
Age  91 month 10 you have $649,512.87
Age  91 month 11 you have $646,054.13
Age  92 month  0 you have $642,592.51
Age  92 month  1 you have $639,128.00
Age  92 month  2 you have $635,660.61
Age  92 month  3 you have $632,190.33
Age  92 month  4 you have $628,717.15
Age  92 month  5 you have $625,241.08
Age  92 month  6 you have $621,762.12
Age  92 month  7 you have $618,280.25
Age  92 month  8 you have $614,795.49
Age  92 month  9 you have $611,307.82
Age  92 month 10 you have $607,817.24
Age  92 month 11 you have $604,323.75
Age  93 month  0 you have $600,827.36
Age  93 month  1 you have $597,328.05
Age  93 month  2 you have $593,825.82
Age  93 month  3 you have $590,320.68
Age  93 month  4 you have $586,812.61
Age  93 month  5 you have $583,301.62
Age  93 month  6 you have $579,787.70
Age  93 month  7 you have $576,270.86
Age  93 month  8 you have $572,751.09
Age  93 month  9 you have $569,228.38
Age  93 month 10 you have $565,702.74
Age  93 month 11 you have $562,174.16
Age  94 month  0 you have $558,642.63
Age  94 month  1 you have $555,108.17
Age  94 month  2 you have $551,570.76
Age  94 month  3 you have $548,030.40
Age  94 month  4 you have $544,487.09
Age  94 month  5 you have $540,940.83
Age  94 month  6 you have $537,391.62
Age  94 month  7 you have $533,839.44
Age  94 month  8 you have $530,284.31
Age  94 month  9 you have $526,726.21
Age  94 month 10 you have $523,165.15
Age  94 month 11 you have $519,601.12
Age  95 month  0 you have $516,034.12
Age  95 month  1 you have $512,464.15
Age  95 month  2 you have $508,891.21
Age  95 month  3 you have $505,315.28
Age  95 month  4 you have $501,736.38
Age  95 month  5 you have $498,154.49
Age  95 month  6 you have $494,569.62
Age  95 month  7 you have $490,981.76
Age  95 month  8 you have $487,390.91
Age  95 month  9 you have $483,797.07
Age  95 month 10 you have $480,200.24
Age  95 month 11 you have $476,600.40
Age  96 month  0 you have $472,997.57
Age  96 month  1 you have $469,391.73
Age  96 month  2 you have $465,782.89
Age  96 month  3 you have $462,171.05
Age  96 month  4 you have $458,556.19
Age  96 month  5 you have $454,938.32
Age  96 month  6 you have $451,317.43
Age  96 month  7 you have $447,693.53
Age  96 month  8 you have $444,066.61
Age  96 month  9 you have $440,436.67
Age  96 month 10 you have $436,803.70
Age  96 month 11 you have $433,167.70
Age  97 month  0 you have $429,528.67
Age  97 month  1 you have $425,886.61
Age  97 month  2 you have $422,241.52
Age  97 month  3 you have $418,593.39
Age  97 month  4 you have $414,942.21
Age  97 month  5 you have $411,288.00
Age  97 month  6 you have $407,630.74
Age  97 month  7 you have $403,970.43
Age  97 month  8 you have $400,307.07
Age  97 month  9 you have $396,640.66
Age  97 month 10 you have $392,971.20
Age  97 month 11 you have $389,298.67
Age  98 month  0 you have $385,623.09
Age  98 month  1 you have $381,944.44
Age  98 month  2 you have $378,262.73
Age  98 month  3 you have $374,577.95
Age  98 month  4 you have $370,890.10
Age  98 month  5 you have $367,199.17
Age  98 month  6 you have $363,505.17
Age  98 month  7 you have $359,808.09
Age  98 month  8 you have $356,107.93
Age  98 month  9 you have $352,404.69
Age  98 month 10 you have $348,698.36
Age  98 month 11 you have $344,988.94
Age  99 month  0 you have $341,276.43
Age  99 month  1 you have $337,560.83
Age  99 month  2 you have $333,842.13
Age  99 month  3 you have $330,120.33
Age  99 month  4 you have $326,395.43
Age  99 month  5 you have $322,667.43
Age  99 month  6 you have $318,936.32
Age  99 month  7 you have $315,202.10
Age  99 month  8 you have $311,464.77
Age  99 month  9 you have $307,724.32
Age  99 month 10 you have $303,980.76
Age  99 month 11 you have $300,234.07
```